import { Component } from '@angular/core';

@Component({
  selector: 'app-customers-grid',
  templateUrl: './customers-grid.component.html',
  styleUrls: ['./customers-grid.component.css']
})
export class CustomersGridComponent {
  allIcons = [
    { imgSource: 'assets/c1.png' },
    { imgSource: 'assets/c2.png' },
    { imgSource: 'assets/c3.png' },
    { imgSource: 'assets/c79.png' },
    { imgSource: 'assets/c4.png' },
    { imgSource: 'assets/c5.png' },
    { imgSource: 'assets/c6.png' },
    { imgSource: 'assets/c7.png' },
    { imgSource: 'assets/c8.png' },
    { imgSource: 'assets/c9.png' },
    { imgSource: 'assets/c10.png' },
    { imgSource: 'assets/c80.jpg' },
    { imgSource: 'assets/c11.png' },
    { imgSource: 'assets/c12.webp' },
    { imgSource: 'assets/c13.png' },
    { imgSource: 'assets/c14.png' },
    { imgSource: 'assets/c15.png' },
    { imgSource: 'assets/c16.png' },
    { imgSource: 'assets/c17.jpg' },
    { imgSource: 'assets/c18.png' },
    { imgSource: 'assets/c19.png' },
    { imgSource: 'assets/c20.jpg' },
    { imgSource: 'assets/c21.png' },
    { imgSource: 'assets/c22.png' },
    { imgSource: 'assets/c23.jpg' },
    { imgSource: 'assets/c24.jpg' },
    { imgSource: 'assets/c25.png' },
    { imgSource: 'assets/c26.png' },
    { imgSource: 'assets/c27.png' },
    { imgSource: 'assets/c28.jpg' },
    { imgSource: 'assets/c29.png' },
    { imgSource: 'assets/c30.png' },
    { imgSource: 'assets/c31.jpeg' },
    { imgSource: 'assets/c32.png' },
    { imgSource: 'assets/c33.png' },
    // { imgSource: 'assets/c34.png' }, delete
    { imgSource: 'assets/c35.jpg' },
    { imgSource: 'assets/c36a.jpg' },
    { imgSource: 'assets/c36b.png' },
    { imgSource: 'assets/c36c.png' },
    { imgSource: 'assets/c37.jpg' },
    { imgSource: 'assets/c38.jpg' },
    { imgSource: 'assets/c39.jpg' },
    { imgSource: 'assets/c40.png' },
    { imgSource: 'assets/c41.jpg' },
    { imgSource: 'assets/c42.jpg' },
    { imgSource: 'assets/c43.jpg' },
    { imgSource: 'assets/c44.jpg' },
    { imgSource: 'assets/c45.jpg' },
    // { imgSource: 'assets/c46.png' }, delete
    { imgSource: 'assets/c47.jpg' },
    { imgSource: 'assets/c48.jpg' },
    { imgSource: 'assets/c49.jpg' },
    { imgSource: 'assets/c50.png' },
    { imgSource: 'assets/c51.jpg' },
    { imgSource: 'assets/c52.png' },
    { imgSource: 'assets/c53.jpg' },
    { imgSource: 'assets/c53b.jpg' },
    { imgSource: 'assets/c54.jpg' },
    { imgSource: 'assets/c55.jpg' },
    { imgSource: 'assets/c56.jpg' },
    { imgSource: 'assets/c57.png' },
    { imgSource: 'assets/c58.png' },
    { imgSource: 'assets/c59.png' },
    { imgSource: 'assets/c60.jpg' },
    { imgSource: 'assets/c61.jpeg' },
    { imgSource: 'assets/c62.png' },
    { imgSource: 'assets/c63.png' },
    { imgSource: 'assets/c64.jpeg' },
    { imgSource: 'assets/c65.jpeg' },
    { imgSource: 'assets/c66.png' },
    { imgSource: 'assets/c67.png' },
    { imgSource: 'assets/c68.png' },
    { imgSource: 'assets/c69.png' },
    { imgSource: 'assets/c70.jpg' },
    { imgSource: 'assets/c71.png' },
    { imgSource: 'assets/c72.jpg' },
    { imgSource: 'assets/c73.png' },
    { imgSource: 'assets/c74.png' },
    { imgSource: 'assets/c75.jpg' },
    { imgSource: 'assets/c77.png' },
    { imgSource: 'assets/c78.png' },
    { imgSource: 'assets/c81.png' },
    { imgSource: 'assets/c82.png' },
    { imgSource: 'assets/c83.png' },
    { imgSource: 'assets/c84.png' },
    { imgSource: 'assets/c85.jpeg' },
    { imgSource: 'assets/c86.png' },
  ]
}
